[package]
name = "juggernaut-iris"
version = "0.1.0"
authors = ["Afshin Mehrabani <afshin.meh@gmail.com>"]

[dependencies]
stdweb = "0.1.1"
libc = "0.2.26"
juggernaut = "0.9.0"
serde = "1.0.10"
csv = "1.0.0-beta.4"
serde_derive = "1.0.10"
serde_json = "*"
itertools="*"
